// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("AnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("AnswerOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("CourseId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.GradedAttempt", b =>
                {
                    b.Property<Guid>("GradedAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GradedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradedItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("GradedAttemptId");

                    b.HasIndex("UserId");

                    b.ToTable("GradedAttempts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.GradedItem", b =>
                {
                    b.Property<Guid>("GradedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("GradedItemType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAutoGraded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<string>("SubmissionGuidelines")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("GradedItemId");

                    b.HasIndex("LessonItemId")
                        .IsUnique();

                    b.ToTable("GradedItems");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("LanguageId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "en",
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 336, DateTimeKind.Utc).AddTicks(3424),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "ja",
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 336, DateTimeKind.Utc).AddTicks(3438),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Japanese"
                        },
                        new
                        {
                            LanguageId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "ko",
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 336, DateTimeKind.Utc).AddTicks(3441),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Korean"
                        },
                        new
                        {
                            LanguageId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "zh",
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 336, DateTimeKind.Utc).AddTicks(3442),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Chinese"
                        },
                        new
                        {
                            LanguageId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "es",
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 336, DateTimeKind.Utc).AddTicks(3444),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Code = "fr",
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 336, DateTimeKind.Utc).AddTicks(3446),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Code = "de",
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 336, DateTimeKind.Utc).AddTicks(3447),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Code = "vi",
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 336, DateTimeKind.Utc).AddTicks(3449),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vietnamese"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("LessonId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LessonItem", b =>
                {
                    b.Property<Guid>("LessonItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("LessonItemId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonItems");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LessonResource", b =>
                {
                    b.Property<Guid>("LessonResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<long?>("DurationInSeconds")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDownloadable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("LessonResourceId");

                    b.HasIndex("LessonItemId");

                    b.ToTable("LessonResources");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ModuleId");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("text");

                    b.Property<string>("CounterAccountBankName")
                        .HasColumnType("text");

                    b.Property<string>("CounterAccountName")
                        .HasColumnType("text");

                    b.Property<string>("CounterAccountNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentLinkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawWebhookData")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PaymentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<Guid>("GradedItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId");

                    b.HasIndex("GradedItemId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuestionSubmission", b =>
                {
                    b.Property<Guid>("QuestionSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<Guid>("GradedAttemptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoGraded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionSubmissionId");

                    b.HasIndex("GradedAttemptId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionSubmissions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SubmissionAnswerOption", b =>
                {
                    b.Property<Guid>("SubmissionAnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.HasKey("SubmissionAnswerOptionId");

                    b.HasIndex("AnswerOptionId");

                    b.HasIndex("QuestionSubmissionId");

                    b.ToTable("SubmissionAnswerOptions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerfied")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 340, DateTimeKind.Utc).AddTicks(5414),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Student1@gmail.com",
                            FullName = "Student1",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 70, 125, 146, 217, 158, 229, 194, 96, 228, 4, 211, 82, 173, 28, 112, 15, 149, 16, 135, 210, 90, 147, 243, 133, 65, 24, 224, 102, 224, 166, 14, 66, 84, 129, 215, 167, 89, 48, 24, 154, 29, 198, 24, 53, 240, 183, 101, 87, 23, 198, 38, 163, 174, 22, 240, 136, 130, 107, 222, 80, 63, 65, 189, 119 },
                            PasswordSalt = new byte[] { 58, 14, 60, 95, 68, 64, 132, 246, 245, 249, 212, 61, 247, 190, 29, 35, 116, 200, 118, 120, 137, 227, 45, 176, 125, 46, 17, 219, 145, 8, 107, 132, 15, 210, 128, 28, 38, 79, 50, 210, 190, 114, 92, 211, 155, 28, 40, 125, 89, 161, 133, 210, 19, 75, 186, 2, 245, 227, 61, 160, 49, 47, 88, 103, 117, 24, 55, 4, 187, 95, 95, 107, 198, 223, 33, 95, 170, 133, 27, 32, 236, 153, 202, 165, 98, 152, 62, 71, 129, 162, 56, 5, 207, 186, 101, 155, 130, 18, 89, 19, 250, 80, 76, 133, 81, 67, 24, 240, 69, 226, 190, 192, 163, 31, 240, 37, 199, 171, 15, 27, 228, 34, 68, 97, 177, 18, 223, 168 },
                            Role = 2
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 340, DateTimeKind.Utc).AddTicks(5421),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Student2@gmail.com",
                            FullName = "Student2",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 252, 226, 93, 93, 216, 223, 117, 255, 11, 145, 152, 29, 142, 206, 90, 216, 122, 153, 219, 83, 144, 214, 99, 239, 2, 57, 73, 245, 75, 214, 4, 12, 148, 111, 4, 3, 9, 116, 185, 48, 239, 126, 131, 121, 2, 165, 247, 168, 211, 214, 10, 242, 113, 225, 133, 223, 60, 126, 126, 165, 235, 77, 37, 156 },
                            PasswordSalt = new byte[] { 87, 200, 226, 136, 48, 163, 28, 61, 197, 179, 79, 176, 143, 232, 58, 104, 73, 34, 198, 117, 134, 127, 174, 247, 172, 35, 210, 132, 208, 2, 204, 32, 226, 27, 62, 252, 140, 227, 218, 178, 199, 140, 79, 189, 111, 138, 114, 100, 33, 152, 39, 75, 110, 12, 36, 7, 39, 163, 7, 6, 252, 80, 84, 30, 143, 100, 191, 12, 157, 55, 186, 225, 22, 172, 0, 89, 108, 232, 152, 26, 244, 59, 42, 207, 2, 245, 10, 65, 5, 118, 138, 17, 90, 68, 75, 130, 197, 37, 19, 187, 174, 28, 114, 33, 253, 76, 161, 137, 28, 105, 193, 61, 100, 222, 204, 104, 31, 154, 203, 197, 220, 193, 110, 175, 22, 75, 240, 101 },
                            Role = 2
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 340, DateTimeKind.Utc).AddTicks(5424),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Instructor@gmail.com",
                            FullName = "Instructor",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 117, 39, 137, 24, 69, 41, 14, 128, 160, 150, 252, 160, 172, 234, 211, 35, 121, 245, 107, 36, 40, 35, 115, 167, 216, 29, 188, 243, 47, 48, 194, 89, 145, 77, 150, 83, 207, 177, 87, 104, 20, 78, 101, 188, 87, 76, 191, 147, 22, 210, 241, 221, 117, 185, 87, 84, 244, 58, 63, 140, 234, 21, 217, 45 },
                            PasswordSalt = new byte[] { 186, 48, 39, 20, 120, 220, 121, 92, 148, 231, 215, 173, 112, 38, 114, 25, 128, 222, 24, 219, 155, 84, 173, 110, 93, 172, 249, 137, 171, 31, 94, 66, 84, 58, 53, 61, 135, 168, 65, 39, 14, 89, 91, 229, 149, 118, 51, 133, 8, 170, 112, 3, 191, 47, 14, 11, 119, 22, 207, 171, 82, 105, 229, 107, 228, 159, 158, 79, 77, 153, 42, 183, 107, 61, 129, 128, 3, 185, 89, 79, 101, 203, 124, 89, 129, 160, 133, 212, 143, 3, 35, 168, 104, 9, 88, 244, 221, 101, 157, 75, 39, 246, 56, 12, 112, 18, 23, 97, 176, 210, 158, 30, 47, 157, 211, 158, 14, 26, 25, 157, 136, 201, 102, 11, 116, 135, 183, 251 },
                            Role = 1
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 29, 17, 12, 48, 340, DateTimeKind.Utc).AddTicks(5426),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Email = "Admin@gmail.com",
                            FullName = "Admin",
                            IsDeleted = false,
                            IsVerfied = true,
                            PasswordHash = new byte[] { 175, 167, 223, 218, 40, 210, 91, 42, 189, 58, 19, 28, 192, 169, 181, 165, 196, 67, 135, 230, 24, 176, 176, 208, 146, 5, 203, 196, 87, 240, 2, 106, 43, 59, 61, 186, 169, 99, 104, 166, 75, 219, 233, 130, 168, 66, 112, 51, 104, 96, 19, 248, 211, 123, 126, 12, 183, 133, 3, 28, 116, 184, 182, 34 },
                            PasswordSalt = new byte[] { 205, 239, 213, 75, 119, 170, 188, 242, 182, 90, 191, 224, 65, 117, 239, 19, 197, 228, 130, 23, 131, 233, 73, 212, 28, 111, 157, 207, 191, 211, 63, 148, 187, 135, 154, 102, 178, 0, 66, 209, 5, 44, 53, 155, 38, 18, 65, 228, 244, 102, 43, 100, 252, 237, 77, 219, 255, 206, 209, 172, 175, 164, 171, 231, 98, 56, 97, 254, 61, 232, 23, 141, 69, 113, 77, 163, 225, 82, 20, 46, 84, 125, 226, 117, 169, 254, 119, 42, 162, 29, 121, 243, 22, 191, 235, 208, 221, 251, 240, 95, 4, 181, 71, 77, 100, 252, 249, 6, 36, 227, 65, 207, 239, 125, 230, 202, 255, 201, 233, 108, 233, 6, 172, 241, 152, 69, 85, 88 },
                            Role = 0
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.UserLessonProgress", b =>
                {
                    b.Property<Guid>("LessonProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletionPercent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastWatchedSecond")
                        .HasColumnType("integer");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LessonProgressId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLessonProgresses");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Wallet", b =>
                {
                    b.Property<Guid>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PendingBalance")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalWithdrawn")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("WalletTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BalanceAfterTransaction")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("WalletTransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.AnswerOption", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Course", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Language", "Language")
                        .WithMany("Courses")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Enrollment", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.GradedAttempt", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.GradedItem", "GradedItem")
                        .WithMany("GradedAttempts")
                        .HasForeignKey("GradedAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany("GradedAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.GradedItem", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LessonItem", "LessonItem")
                        .WithOne("GradedItem")
                        .HasForeignKey("DataAccessLayer.Entities.GradedItem", "LessonItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonItem");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Lesson", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LessonItem", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Lesson", "Lesson")
                        .WithMany("LessonItems")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LessonResource", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.LessonItem", "LessonItem")
                        .WithMany("LessonResources")
                        .HasForeignKey("LessonItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonItem");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Module", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Course", "Course")
                        .WithMany("Payments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Enrollment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Question", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.GradedItem", "GradedItem")
                        .WithMany("Questions")
                        .HasForeignKey("GradedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedItem");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuestionSubmission", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.GradedAttempt", "GradedAttempt")
                        .WithMany("QuestionSubmissions")
                        .HasForeignKey("GradedAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Question", "Question")
                        .WithMany("QuestionSubmissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradedAttempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SubmissionAnswerOption", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.AnswerOption", "AnswerOption")
                        .WithMany("SubmissionAnswerOptions")
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.QuestionSubmission", "QuestionSubmission")
                        .WithMany("SubmissionAnswerOptions")
                        .HasForeignKey("QuestionSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");

                    b.Navigation("QuestionSubmission");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.UserLessonProgress", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Lesson", "Lesson")
                        .WithMany("UserLessonProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany("UserLessonProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Wallet", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("DataAccessLayer.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.WalletTransaction", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Wallet", "Wallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.AnswerOption", b =>
                {
                    b.Navigation("SubmissionAnswerOptions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Modules");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Enrollment", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.GradedAttempt", b =>
                {
                    b.Navigation("QuestionSubmissions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.GradedItem", b =>
                {
                    b.Navigation("GradedAttempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Language", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Lesson", b =>
                {
                    b.Navigation("LessonItems");

                    b.Navigation("UserLessonProgresses");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.LessonItem", b =>
                {
                    b.Navigation("GradedItem");

                    b.Navigation("LessonResources");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Module", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("QuestionSubmissions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuestionSubmission", b =>
                {
                    b.Navigation("SubmissionAnswerOptions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("GradedAttempts");

                    b.Navigation("Payments");

                    b.Navigation("UserLessonProgresses");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Wallet", b =>
                {
                    b.Navigation("WalletTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
